# 公共配置文件
spring:
  application:
    name: tianCai_API_backend
  # 默认 dev 环境
  profiles:
    active: dev
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session 配置
  session:
    # todo 取消注释开启分布式 session（须先配置 Redis）
    # store-type: redis
    # 30 天过期
    timeout: 2592000
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tianCaiAPI
    username: root
    password: xxxxx
  #  邮箱配置 todo 修改为自己的邮箱发送配置
  mail:
    host: smtp.qq.com
    username: xxxxx
    password: xxxxx
    emailFrom: xxxxx

    properties:
      mail:
        smtp:
          ssl:
            enable: true
    port: 25
#    port: 587
  # Redis 配置
  # todo 需替换配置，然后取消注释
  redis:
    database: 6
    host: localhost
    port: 6379
    timeout: 5000
  # Elasticsearch 配置
  # todo 需替换配置，然后取消注释
#  elasticsearch:
#    uris: http://localhost:9200
#    username: root
#    password: 123456
  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB
server:
  address: 0.0.0.0
  port: 8101
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
# 微信相关
wx:
  # 微信公众平台
  # todo 需替换配置
  mp:
    token: xxx
    aesKey: xxx
    appId: xxx
    secret: xxx
    config-storage:
      http-client-type: HttpClient
      key-prefix: wx
      redis:
        host: 127.0.0.1
        port: 6379
      type: Memory
  # 微信开放平台
  # todo 需替换配置
  open:
    appId: xxx
    appSecret: xxx
# 对象存储
# todo 需替换配置

tiancaiapi:
  client:
    access-key: xxxxx
    secret-key: xxxxx
dubbo:
  application:
    name: dubbo-springboot-demo-provider
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://localhost:8848
oss:
  client:
    endpoint: xxxxx
    access-key: xxxxx
    secret-key: xxxxx
    bucket: xxxxx

# 支付宝支付配置
alipay:
  appId: xxxxx
  sellerId: xxxxx
  # 本地测试用ngrok内网穿透，这个内网穿透地址，可以修改为自己的。上线修改为后端的接口地址即可
  notifyUrl: http://kqft4a.natappfree.cc/api/productOrder/notify/order
  returnUrl: xxxxx
  sandbox: true
  private-key: xxxxx
  ali-pay-public-key: xxxx